language: swift
os: osx
osx_image: xcode10.2
xcode_project: hackernews-stories.xcodeproj
xcode_scheme: hackernews-stories-Develop
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'hackernews-stories'
