language: swift
os: osx
osx_image: xcode10.2
xcode_workspace: hackernews-stories.xcworkspace
xcode_scheme: hackernews-stories-Develop
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X

before_install:
 - gem install cocoapods
 - pod repo update
 - pod install

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'hackernews-stories'
